services:
  auth-api:
    image: ghcr.io/deathfull/evently-auth-api:dev
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
  events-api:
    image: ghcr.io/deathfull/evently-events-api:dev
    ports:
      - "3001:3000"
    deploy:
      replicas: 2
  transactions-api:
    image: ghcr.io/deathfull/evently-transactions-api:dev
    ports:
      - "3002:3000"
    deploy:
      replicas: 2
  users-api:
    image: ghcr.io/deathfull/evently-users-api:dev
    ports:
      - "3003:3000"
    deploy:
      replicas: 2